### ISSUE TITLE
steedos-config.yml 支持使用环境变量

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#164]
可以先在加载的时候集中替换一下。 
参考 docker-compose.yml 
${ROOT_URL} 格式表示环境变量

**Comment by baozhoutao** [comment]
示例
```
env:
  PORT: 5000
  ROOT_URL: http://127.0.0.1:${PORT}
  DB_SERVER: 127.0.0.1
  MONGO_URL: mongodb://${DB_SERVER}/steedos
datasources:
  default:
    connection: 
      url: ${MONGO_URL}
    objectFiles: [./src/**]
```
