### ISSUE TITLE
模版项目未能加载对象

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#196]
模版项目少了 objectFiles 配置参数
```yml
datasources:
  default:
    connection: 
      host: 127.0.0.1
      database: steedos
      objectFiles: "./src/**"
```
