### ISSUE TITLE
select 类型字段 options 定义格式

### ISSUE THREAD

**Issue by hotlong** [steedos/object-server#222]
目前不支持
 
```
  status:
    label: 项目状态
    type: select
    options: 合同未签订,进行中,已完成,已验收,已付款
```
 
```
  status:
    label: 项目状态
    type: select
    options: 
      - 合同未签订
      - 进行中
      - 已完成
      - 已验收
      - 已付款
```
